### ISSUE TITLE
Query about the data.

### ISSUE THREAD

**Issue by liuquande** [I2Cvb/mp-mri-prostate#1]
Thanks to your effort first.

I meet some problem when downloading I2CVB data from (https://zenodo.org/record/61163#.XMQfsXUzZhF) and
(https://zenodo.org/record/162228#.XMQ-sHUzZhF). 

The suffix is quite strange with some '.bin' '.gz' or '.aa'. Could you please tell me how to extract the data out from these files.

Thank you so much! Have a nice day.

**Comment by a6225301** [comment]
hi, any solution to open those files ? Thanks a lot. @liuquande
